### ISSUE TITLE
Few questions

### ISSUE THREAD

**Issue by alexspace360** [NebraLtd/AnyBeam#10]
1- official website ? 
2- official Email ? 
3- can i project at 40 cm away without losing details ?

**Comment by ryanteck** [comment]
Hi @alexspace360 ,

1 - Our website for selling the units is at https://uk.pi-supply.com/products/nebra-anybeam?, https://uk.pi-supply.com/products/nebra-anybeam-developer-kit & https://uk.pi-supply.com/products/nebra-anybeam-hat-laser-projector-for-the-raspberry-pi

2 - You can email us on sales@pi-supply.com

3 - 40CM would be fine but likely require content that's big for it to be clear. Typically we recommend from 1M distance but it can be closer.

**Comment by ryanteck** [comment]
Hi @alexspace360 ,

We've taken a couple of images showing a video playing at about a 40CM distance. I hope these help.

![IMG_20201127_1055281](https://user-images.githubusercontent.com/1104745/100442850-a3722700-30a0-11eb-9709-07c4421c8edf.jpg)
![IMG_20201127_1054189](https://user-images.githubusercontent.com/1104745/100442853-a4a35400-30a0-11eb-89d9-a553419ded6e.jpg)
![IMG_20201127_1054562](https://user-images.githubusercontent.com/1104745/100442854-a53bea80-30a0-11eb-8816-53736bd3cbbb.jpg)
