### ISSUE TITLE
Raspberry Pi 0 W - no image

### ISSUE THREAD

**Issue by jahevos** [NebraLtd/AnyBeam#11]
I cant get the image from my raspberry pi 0w dpi_video out. Basically I am stuck with the nebra startup screen. I tried this under a number of distros - libreelec,kodi,raspian and raspberry os. I get, however, a proper image when setting it up with a rpi 2.
I tried all of the suggested config methods from the user guide but to no avail.
Also no matter which power supply and usb wire I use I do get a yellow flash in the top right corner. 
Any Input would be appreciated - maybe anyone else ran into these kind of problems.

cheers 
J

**Comment by ryanteck** [comment]
Hi @jahevos ,

If it's where it works with your Raspberry Pi 2 fine with the same SD Card image as you're trying on your Zero I would suspect it could be a faulty Pi Zero W.

Did you buy one with the header pre-soldered or did you solder it yourself? It could be one of the joints isn't quite good enough for the signals required for the HAT.

**Comment by jahevos** [comment]
Hi Ryan thanks for your quick reply.
I got a pre-soldered pi, so it should be okay but I will look into it later. Cheers

On November 30, 2020 1:13:16 PM GMT+01:00, Ryan Walmsley <notifications@github.com> wrote:
>Hi @jahevos ,
>
>If it's where it works with your Raspberry Pi 2 fine with the same SD
>Card image as you're trying on your Zero I would suspect it could be a
>faulty Pi Zero W.
>
>Did you buy one with the header pre-soldered or did you solder it
>yourself? It could be one of the joints isn't quite good enough for the
>signals required for the HAT.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/NebraLtd/AnyBeam/issues/11#issuecomment-735749396

-- 
Jan VOSSMERBAEUMER
Am Berg 3
6912 Hörbranz
Austria

Tel +491521 8381465

**Comment by ryanteck** [comment]
That *should* be fine then. If you could take a picture of the header I can see if there's any visual defect with it but it would be odd if it's pre-soldered.

**Comment by jahevos** [comment]
Hi Ryan,

I gave everything another go, with no success. I'll get another pi zero and see what happens. I'll keep you posted on the outcome. Best j

On November 30, 2020 1:47:09 PM GMT+01:00, Ryan Walmsley <notifications@github.com> wrote:
>That *should* be fine then. If you could take a picture of the header I
>can see if there's any visual defect with it but it would be odd if
>it's pre-soldered.
>
>
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/NebraLtd/AnyBeam/issues/11#issuecomment-735765186

-- 
Jan VOSSMERBAEUMER
Am Berg 3
6912 Hörbranz
Austria

Tel +491521 8381465

**Comment by jahevos** [comment]
Sorry for the late answer. Fault was defective rpi0 -the new one resolved the issue thanks
