### ISSUE TITLE
Model specification: Laser Module from AnyBeam 

### ISSUE THREAD

**Issue by beniroquai** [NebraLtd/AnyBeam#15]
Is there any information about the Model you use in the Anybeam Nebra? I'm curious which brand you have used there since we want to compare that in an upcaming manuscript, where we used a Sony Laser Projector. It seems it has different laser wavelength and does not need a freeform optics in front of the laser scanner. 

It would be great if you can provide some information. 

Thanks a lot!

**Comment by shawaj** [comment]
The module we use is from [Ultimems](http://www.ultimems.com/en/index.html)

**Comment by beniroquai** [comment]
Great thanks! :)
