### ISSUE TITLE
AnyBeam HAT to OE Sensor FPC Connector/Housing Specs Please.

### ISSUE THREAD

**Issue by pixma** [NebraLtd/AnyBeam#16]
Can I have the spec of the FPC connector where the FPC Cable is used to connect the HAT and the Mems Lase Sensor Module?
If yes, I would like to know more about the connector's
- Pitch?
- Top Contact or Bottom Contact?
- Positions: 30 | OK
- Voltage Rating

and so on and so forth, of the FPC Connector. So we can choose the FPC Connector correctly to take in the FPC Cable which comes out from OE Mems Sensor Module Itself.

Regards,

**Comment by shawaj** [comment]
![image004](https://user-images.githubusercontent.com/3359418/102328791-6f8f7080-3f7f-11eb-8455-bac87d9708c9.jpg)
Pinout diagram for it.

**Comment by pixma** [comment]
Hi,

Thank you @shawaj for the pinout description, but, I am looking for something like this, if you can confirm if it is 5mm pitch bottom contact FPC Connector. Or if the PFC connector has some other spec?

![image](https://user-images.githubusercontent.com/2097509/102332461-1ee53b00-3fb2-11eb-9bdd-f1773d05c4bd.png)

**Comment by shawaj** [comment]
@pixma ah yes sorry should have said I'll have that detail for you soon

**Comment by pixma** [comment]
Hi,

I am looking forward to that info.
It's important info/ Hence, this is a gentle reminder @shawaj or anyone who have this info, can you please share when you can.

Regards

**Comment by shawaj** [comment]
![20201224_012442](https://user-images.githubusercontent.com/3359418/103048569-f5ff1000-4586-11eb-93f1-0073e7801b53.png)

So it's 30 pin and 0.5mm pitch

**Comment by shawaj** [comment]
@pixma was that what you needed?

**Comment by pixma** [comment]
Thank you @shawaj , yes this information is good enough to select the mating connector.

Regards.
