### ISSUE TITLE
Adding CAD files for HAT?

### ISSUE THREAD

**Issue by beniroquai** [NebraLtd/AnyBeam#3]
Today we received the Anybeam HAT. Finally! Nice! And it works. 

I was wondering if you can provide a 3D CAD model (e.g. STL/STP) for the assembly so that we can start building a case for it. 

Thanks!

**Comment by ryanteck** [comment]
Hi @beniroquai ,

We'll look into it and see if we can generate one.

**Comment by shawaj** [comment]
@beniroquai  We should have these today for you.

**Comment by beniroquai** [comment]
@shawaj any update? :)

**Comment by ryanteck** [comment]
We should have an update shortly, I believe we've got 2 of them generated now and are working on the last.

**Comment by shawaj** [comment]
Closed by https://github.com/NebraLtd/AnyBeam/commit/5d639666c64d2efbbc10fafe64d329aa01558935

**Comment by shawaj** [comment]
3D files are here - https://github.com/NebraLtd/AnyBeam/tree/master/Hardware/3D

**Comment by shawaj** [comment]
@beniroquai it is not a priority for us at the moment, so apologies but we will not be able to do this
